blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://github.com/resemi/resemi-admin/discussions
    about: Ask questions and discuss with other Resemi users in real time.
  - name: Questions & Discussions
    url: https://github.com/resemi/resemi-admin/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
